Project-Condor:
  org: ss14-art
  project: 2
  inbox: Inbox
  labels:
    "W: В прогрессе": "В прогрессе"
    "W: Обсуждение": "Проектирование и обсуждение"
    "W: Невыполненные": "Список невыполненных задач"
    "W: Следующее": "Следующее"
