"Changes: Спрайты":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Changes: Карта":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"Changes: UI":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"Changes: Шейдеры":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Changes: Аудио":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"Changes: Нету C#":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "!**/*.cs"

"Changes: Есть C#":
- changed-files:
  - any-glob-to-any-file: '**/*.cs'

"Changes: Прототипы":
- changed-files:
  - any-glob-to-any-file: 'Resources/Prototypes/**/*.yml'

#Starlight exclusive label
"Changes: Гайдбуки":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/ServerInfo/**/*.xml'
    - 'Resources/Prototypes/Guidebook/**/*.yml'
    - 'Resources/Prototypes/*/Guidebook/**/*.xml'