using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Content.Shared._OpenSpace.Genetics;
using Robust.Client.UserInterface.XAML;
using System.Collections.Generic;
using System;
using Robust.Shared.Localization;

namespace Content.Client._OpenSpace.Genetics.UI
{
    public sealed partial class GeneticsConsoleWindow : DefaultWindow
    {
        private readonly TabContainer _mainTabContainer;
        private readonly BoxContainer _modifyUiTab;
        private readonly BoxContainer _modifySeTab;
        private readonly BoxContainer _transferBuffersTab;
        private readonly BoxContainer _rejuvenatorsTab;
        private readonly Button _irradiateButton;
        private readonly Button _uiIrradiateButton;
        private readonly Button _inject5Button;
        private readonly Button _inject10Button;
        private readonly Button _inject20Button;
        private readonly Button _inject30Button;
        private readonly Button _inject50Button;
        private readonly Button _injectAllButton;
        private readonly Button _ejectBeakerButton;
        private readonly Button _doorLockButton;
        private readonly Label _occupantNameLabel;
        private readonly Label _occupantStatusLabel;
        private readonly ProgressBar _healthBar;
        private readonly Label _healthLabel;
        private readonly ProgressBar _radiationBar;
        private readonly Label _radiationLabel;
        private readonly Label _beakerLabel;
        private readonly Label _beakerVolumeLabel;
        private readonly GridContainer _enzymeGrid;
        private readonly GridContainer _uiGrid;
        private readonly BoxContainer _transferBuffersContainer;
        private readonly List<TransferBufferRow> _transferBufferRows = new();

        public event Action<int, bool>? OnSelectBlock;
        public event Action<int, bool>? OnIrradiateBlock;
        public event Action<int>? OnInject;
        public event Action? OnEjectBeaker;
        public event Action<int, int, string, bool>? OnModifySubGene; 
        public event Action<int, GeneticsBufferCopyMode>? OnStoreBuffer;
        public event Action<int, GeneticsBufferTransferTarget>? OnTransferBuffer;
        public event Action<bool>? OnToggleScannerLock;

        public GeneticsConsoleWindow()
        {
            RobustXamlLoader.Load(this);

            _mainTabContainer = this.FindControl<TabContainer>("MainTabContainer");
            _modifyUiTab = this.FindControl<BoxContainer>("ModifyUITab");
            _modifySeTab = this.FindControl<BoxContainer>("ModifySETab");
            _transferBuffersTab = this.FindControl<BoxContainer>("TransferBuffersTab");
            _rejuvenatorsTab = this.FindControl<BoxContainer>("RejuvenatorsTab");
            _irradiateButton = this.FindControl<Button>("IrradiateButton");
            _uiIrradiateButton = this.FindControl<Button>("UiIrradiateButton");
            _inject5Button = this.FindControl<Button>("Inject5Button");
            _inject10Button = this.FindControl<Button>("Inject10Button");
            _inject20Button = this.FindControl<Button>("Inject20Button");
            _inject30Button = this.FindControl<Button>("Inject30Button");
            _inject50Button = this.FindControl<Button>("Inject50Button");
            _injectAllButton = this.FindControl<Button>("InjectAllButton");
            _ejectBeakerButton = this.FindControl<Button>("EjectBeakerButton");
            _doorLockButton = this.FindControl<Button>("DoorLockButton");
            _occupantNameLabel = this.FindControl<Label>("OccupantNameLabel");
            _occupantStatusLabel = this.FindControl<Label>("OccupantStatusLabel");
            _healthBar = this.FindControl<ProgressBar>("HealthBar");
            _healthLabel = this.FindControl<Label>("HealthLabel");
            _radiationBar = this.FindControl<ProgressBar>("RadiationBar");
            _radiationLabel = this.FindControl<Label>("RadiationLabel");
            _beakerLabel = this.FindControl<Label>("BeakerLabel");
            _beakerVolumeLabel = this.FindControl<Label>("BeakerVolumeLabel");
            _enzymeGrid = this.FindControl<GridContainer>("EnzymeGrid");
            _uiGrid = this.FindControl<GridContainer>("UIGrid");
            _transferBuffersContainer = this.FindControl<BoxContainer>("TransferBuffersContainer");

            InitializeTransferBuffers();

            TabContainer.SetTabTitle(_modifyUiTab, Loc.GetString("genetics-console-tab-ui"));
            TabContainer.SetTabTitle(_modifySeTab, Loc.GetString("genetics-console-tab-se"));
            TabContainer.SetTabTitle(_transferBuffersTab, Loc.GetString("genetics-console-tab-buffers"));
            TabContainer.SetTabTitle(_rejuvenatorsTab, Loc.GetString("genetics-console-tab-rejuvenators"));

            _mainTabContainer.CurrentTab = 1;

            _irradiateButton.OnPressed += _ =>
            {
                if (_lastSelectedWasUi && _lastSelectedUiBlock != -1)
                    OnIrradiateBlock?.Invoke(_lastSelectedUiBlock, true);
                else if (!_lastSelectedWasUi && _lastSelectedSeBlock != -1)
                    OnIrradiateBlock?.Invoke(_lastSelectedSeBlock, false);
            };

            _uiIrradiateButton.OnPressed += _ =>
            {
                if (_lastSelectedUiBlock != -1)
                    OnIrradiateBlock?.Invoke(_lastSelectedUiBlock, true);
            };

            _inject5Button.OnPressed += _ => OnInject?.Invoke(5);
            _inject10Button.OnPressed += _ => OnInject?.Invoke(10);
            _inject20Button.OnPressed += _ => OnInject?.Invoke(20);
            _inject30Button.OnPressed += _ => OnInject?.Invoke(30);
            _inject50Button.OnPressed += _ => OnInject?.Invoke(50);
            _injectAllButton.OnPressed += _ => OnInject?.Invoke(9999);
            _ejectBeakerButton.OnPressed += _ => OnEjectBeaker?.Invoke();
            _doorLockButton.OnPressed += _ => OnToggleScannerLock?.Invoke(_doorLockButton.Pressed);
        }

        private int _lastSelectedUiBlock = -1;
        private int _lastSelectedSeBlock = -1;
        private bool _lastSelectedWasUi;

        public void UpdateState(GeneticsConsoleBoundUserInterfaceState state)
        {
            _occupantNameLabel.Text = state.OccupantName;
            _doorLockButton.Disabled = !state.HasScanner;
            _doorLockButton.Pressed = state.ScannerLocked;
            _doorLockButton.Text = state.ScannerLocked
                ? Loc.GetString("genetics-console-lock-locked")
                : Loc.GetString("genetics-console-lock-unlocked");
            _occupantStatusLabel.Text = state.IsOccupantAlive
                ? Loc.GetString("genetics-console-status-alive")
                : Loc.GetString("genetics-console-status-dead");
            _occupantStatusLabel.FontColorOverride = state.IsOccupantAlive ? Color.Green : Color.Red;

            _healthBar.MaxValue = (float)state.MaxHealth;
            _healthBar.Value = (float)state.CurrentHealth;
            float healthPercent = (state.MaxHealth > 0) ? ((float)state.CurrentHealth / (float)state.MaxHealth) : 0;
            _healthLabel.Text = $"{healthPercent:P0}";

            _radiationBar.MaxValue = 100f; 
            _radiationBar.Value = state.RadiationExposure;
            _radiationLabel.Text = $"{state.RadiationExposure}%";

            _lastSelectedUiBlock = state.SelectedUiBlock;
            _lastSelectedSeBlock = state.SelectedSeBlock;
            _lastSelectedWasUi = _mainTabContainer.CurrentTab == FindTabIndex(_modifyUiTab);
            PopulateEnzymeGrid(state.SeDna, state.SelectedSeBlock);
            PopulateUIGrid(state.UiDna, state.SelectedUiBlock);

            _irradiateButton.Disabled = (_lastSelectedUiBlock == -1 && _lastSelectedSeBlock == -1);
            _uiIrradiateButton.Disabled = _lastSelectedUiBlock == -1;

            if (state.HasBeaker)
            {
                _beakerLabel.Text = state.BeakerLabel;
                _beakerVolumeLabel.Text = Loc.GetString("genetics-console-beaker-volume",
                    ("current", state.BeakerCurrentVolume),
                    ("max", state.BeakerMaxVolume));
                _ejectBeakerButton.Disabled = false;
                _inject5Button.Disabled = state.BeakerCurrentVolume < 5;
                _inject10Button.Disabled = state.BeakerCurrentVolume < 10;
                _inject20Button.Disabled = state.BeakerCurrentVolume < 20;
                _inject30Button.Disabled = state.BeakerCurrentVolume < 30;
                _inject50Button.Disabled = state.BeakerCurrentVolume < 50;
                _injectAllButton.Disabled = state.BeakerCurrentVolume <= 0;
            }
            else
            {
                _beakerLabel.Text = Loc.GetString("genetics-console-beaker-missing");
                _beakerVolumeLabel.Text = Loc.GetString("genetics-console-beaker-volume-empty");
                _ejectBeakerButton.Disabled = true;
                _inject5Button.Disabled = true;
                _inject10Button.Disabled = true;
                _inject20Button.Disabled = true;
                _inject30Button.Disabled = true;
                _inject50Button.Disabled = true;
                _injectAllButton.Disabled = true;
            }

            UpdateTransferBuffers(state);
        }

        private void InitializeTransferBuffers()
        {
            _transferBuffersContainer.DisposeAllChildren();

            for (var i = 0; i < 6; i++)
            {
                var rowContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 2
                };

                var nameLabel = new Label
                {
                    Text = Loc.GetString("genetics-console-buffer-label",
                        ("index", i + 1),
                        ("name", Loc.GetString("genetics-console-buffer-empty"))),
                    StyleClasses = { "LabelSubHeading" }
                };

                var buttonsRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 4
                };

                var uiButton = new Button { Text = Loc.GetString("genetics-console-button-ui"), MinWidth = 110 };
                var uiSeButton = new Button { Text = Loc.GetString("genetics-console-button-ui-se"), MinWidth = 160 };
                var seButton = new Button { Text = Loc.GetString("genetics-console-button-se"), MinWidth = 110 };
                var transferButton = new Button { Text = Loc.GetString("genetics-console-button-transfer"), MinWidth = 90 };
                var syringeButton = new Button { Text = Loc.GetString("genetics-console-button-syringe"), MinWidth = 90 };

                var bufferIndex = i;
                uiButton.OnPressed += _ => OnStoreBuffer?.Invoke(bufferIndex, GeneticsBufferCopyMode.UiOnly);
                uiSeButton.OnPressed += _ => OnStoreBuffer?.Invoke(bufferIndex, GeneticsBufferCopyMode.UiAndSe);
                seButton.OnPressed += _ => OnStoreBuffer?.Invoke(bufferIndex, GeneticsBufferCopyMode.SeOnly);
                transferButton.OnPressed += _ => OnTransferBuffer?.Invoke(bufferIndex, GeneticsBufferTransferTarget.Subject);
                syringeButton.OnPressed += _ => OnTransferBuffer?.Invoke(bufferIndex, GeneticsBufferTransferTarget.Syringe);

                buttonsRow.AddChild(uiButton);
                buttonsRow.AddChild(uiSeButton);
                buttonsRow.AddChild(seButton);
                buttonsRow.AddChild(transferButton);
                buttonsRow.AddChild(syringeButton);

                rowContainer.AddChild(nameLabel);
                rowContainer.AddChild(buttonsRow);

                _transferBuffersContainer.AddChild(rowContainer);

                _transferBufferRows.Add(new TransferBufferRow(nameLabel, uiButton, uiSeButton, seButton, transferButton, syringeButton));
            }
        }

        private void UpdateTransferBuffers(GeneticsConsoleBoundUserInterfaceState state)
        {
            for (var i = 0; i < _transferBufferRows.Count; i++)
            {
                var row = _transferBufferRows[i];
                var hasSubject = state.HasSubject;
                var hasSyringe = state.HasSyringe;

                string name = Loc.GetString("genetics-console-buffer-empty");
                bool hasUi = false;
                bool hasSe = false;

                if (i < state.TransferBuffers.Count)
                {
                    var buffer = state.TransferBuffers[i];
                    name = string.IsNullOrWhiteSpace(buffer.SubjectName)
                        ? Loc.GetString("genetics-console-buffer-empty")
                        : buffer.SubjectName;
                    hasUi = buffer.HasUi;
                    hasSe = buffer.HasSe;
                }

                var flags = string.Empty;
                if (hasUi)
                    flags = Loc.GetString("genetics-console-flag-ui");
                if (hasSe)
                    flags = string.IsNullOrEmpty(flags)
                        ? Loc.GetString("genetics-console-flag-se")
                        : $"{flags}, {Loc.GetString("genetics-console-flag-se")}";

                var display = flags.Length > 0 ? $"{name} ({flags})" : name;
                row.NameLabel.Text = Loc.GetString("genetics-console-buffer-label",
                    ("index", i + 1),
                    ("name", display));

                var hasData = hasUi || hasSe;
                row.UiButton.Disabled = !hasSubject;
                row.UiSeButton.Disabled = !hasSubject;
                row.SeButton.Disabled = !hasSubject;
                row.TransferButton.Disabled = !hasData || !hasSyringe;
                row.SyringeButton.Disabled = !hasData || !hasSyringe;
            }
        }

        private sealed class TransferBufferRow
        {
            public readonly Label NameLabel;
            public readonly Button UiButton;
            public readonly Button UiSeButton;
            public readonly Button SeButton;
            public readonly Button TransferButton;
            public readonly Button SyringeButton;

            public TransferBufferRow(Label nameLabel, Button uiButton, Button uiSeButton, Button seButton, Button transferButton, Button syringeButton)
            {
                NameLabel = nameLabel;
                UiButton = uiButton;
                UiSeButton = uiSeButton;
                SeButton = seButton;
                TransferButton = transferButton;
                SyringeButton = syringeButton;
            }
        }

        private int FindTabIndex(Control tab)
        {
            for (var i = 0; i < _mainTabContainer.ChildCount; i++)
            {
                if (_mainTabContainer.GetChild(i) == tab)
                    return i;
            }

            return -1;
        }

        private void PopulateEnzymeGrid(Dictionary<int, string> dna, int selectedBlock)
        {
            _enzymeGrid.DisposeAllChildren();

            for (int i = 0; i < 55; i++)
            {
                var blockContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new Thickness(2),
                    HorizontalExpand = true
                };

                var isSelected = i == selectedBlock;

                blockContainer.AddChild(new Label
                {
                    Text = (i + 1).ToString(),
                    MinWidth = 30,
                    Align = Label.AlignMode.Right,
                    VAlign = Label.VAlignMode.Center
                });

                blockContainer.AddChild(new Control { MinWidth = 5 });

                string hexBlock = dna.ContainsKey(i) ? dna[i] : "---";
                
                while (hexBlock.Length < 3)
                    hexBlock += "-";
                
                for (int subIndex = 0; subIndex < 3; subIndex++)
                {
                    string hexValue = hexBlock.Length > subIndex ? hexBlock[subIndex].ToString() : "-";
                    
                    var button = new Button
                    {
                        Text = hexValue,
                        MinWidth = 35,
                        MinHeight = 35,
                        Margin = new Thickness(1, 0, 1, 0),
                        StyleClasses = { "OpenLeft" },
                        ToggleMode = true,
                        Pressed = isSelected
                    };

                    int blockIndex = i;
                    int currentSubIndex = subIndex;
                    
                    button.OnPressed += _ =>
                    {
                        _lastSelectedSeBlock = blockIndex;
                        _lastSelectedWasUi = false;
                        button.Pressed = true;
                        OnSelectBlock?.Invoke(blockIndex, false);
                    };

                    blockContainer.AddChild(button);
                }

                _enzymeGrid.AddChild(blockContainer);
            }
        }
        
        private void PopulateUIGrid(Dictionary<int, string> dna, int selectedBlock)
        {
            _uiGrid.DisposeAllChildren();

            for (int i = 0; i < 39; i++)
            {
                var blockContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new Thickness(2),
                    HorizontalExpand = true
                };

                var isSelected = i == selectedBlock;

                blockContainer.AddChild(new Label
                {
                    Text = (i + 1).ToString(),
                    MinWidth = 30,
                    Align = Label.AlignMode.Right,
                    VAlign = Label.VAlignMode.Center
                });

                blockContainer.AddChild(new Control { MinWidth = 5 });

                string hexBlock = dna.ContainsKey(i) ? dna[i] : "---";
                
                while (hexBlock.Length < 3)
                    hexBlock += "-";
                
                for (int subIndex = 0; subIndex < 3; subIndex++)
                {
                    string hexValue = hexBlock.Length > subIndex ? hexBlock[subIndex].ToString() : "-";
                    
                    var button = new Button
                    {
                        Text = hexValue,
                        MinWidth = 35,
                        MinHeight = 35,
                        Margin = new Thickness(1, 0, 1, 0),
                        StyleClasses = { "OpenLeft" },
                        ToggleMode = true,
                        Pressed = isSelected
                    };

                    int blockIndex = i;
                    int currentSubIndex = subIndex;
                    
                    button.OnPressed += _ =>
                    {
                        _lastSelectedUiBlock = blockIndex;
                        _lastSelectedWasUi = true;
                        button.Pressed = true;
                        OnSelectBlock?.Invoke(blockIndex, true);
                    };

                    blockContainer.AddChild(button);
                }

                _uiGrid.AddChild(blockContainer);
            }
        }
    }
}

