using System.Text;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;
using Robust.Shared.IoC;

namespace Content.Client._OpenSpace.Genetics.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GeneModificationConsoleWindow : DefaultWindow
    {
        public GeneModificationConsoleWindow()
        {
            RobustXamlLoader.Load(this);
            GenerateRandomSequence();
        }

        private void GenerateRandomSequence()
        {
            var random = IoCManager.Resolve<IRobustRandom>();

            var  chars = "ATGC0123456789!@#$%^&*()_+={}[]|:;<>,.?/~".ToCharArray();
            var sb = new StringBuilder();

            for (int i = 0; i < 2000; i++)
            {
                sb.Append(random.Pick(chars));
                if (i % 50 == 0 && i > 0) sb.Append('\n');
                else if (i % 5 == 0) sb.Append(' ');
            }

            GeneticSequenceLabel.Text = sb.ToString();
        }
    }
}

