using Content.Shared._OpenSpace.Genetics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System;

namespace Content.Client._OpenSpace.Administration.UI.GrantGene;

[GenerateTypedNameReferences]
public sealed partial class GrantGeneWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private GenePrototype? _selectedGene;

    public event Action<string>? OnGrantGene;

    public GrantGeneWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += _ => UpdateGeneList(SearchBar.Text);
        GeneList.OnItemSelected += GeneSelected;
        GeneList.OnItemDeselected += _ => SetSelectedGene(null);
        GrantButton.OnPressed += _ =>
        {
            if (_selectedGene != null)
                OnGrantGene?.Invoke(_selectedGene.ID);
        };

        UpdateGeneList();
        UpdateGrantButton();
    }

    private void GeneSelected(ItemList.ItemListSelectedEventArgs args)
    {
        SetSelectedGene((GenePrototype) GeneList[args.ItemIndex].Metadata!);
    }

    private void SetSelectedGene(GenePrototype? gene)
    {
        _selectedGene = gene;
        UpdateGrantButton();
    }

    private void UpdateGrantButton()
    {
        if (_selectedGene == null)
        {
            GrantButton.Disabled = true;
            return;
        }

        GrantButton.Disabled = false;
    }

    private void UpdateGeneList(string? filter = null)
    {
        GeneList.Clear();
        var normalized = filter?.Trim().ToLowerInvariant();

        foreach (var gene in _prototypeManager.EnumeratePrototypes<GenePrototype>())
        {
            var display = string.IsNullOrWhiteSpace(gene.Name) ? gene.ID : gene.Name;
            if (!string.IsNullOrEmpty(normalized))
            {
                var haystack = $"{gene.ID} {gene.Name}".ToLowerInvariant();
                if (!haystack.Contains(normalized))
                    continue;
            }

            ItemList.Item item = new(GeneList)
            {
                Metadata = gene,
                Text = display
            };

            GeneList.Add(item);
        }
    }
}
