- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleShadowlingThrall
  name: Shadowling Thrall Role
  components:
  - type: MindRole
    antag: true
    roleType: TeamAntagonist
    subtype: role-subtype-shadowling-thrall
