- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleShadowling
  name: Shadowling Role
  components:
  - type: MindRole
    antagPrototype: Shadowling
    roleType: TeamAntagonist
    subtype: role-subtype-shadowling
